In [ ]:
import tensorflow_datasets as tfds

In [ ]:
import tensorflow as tf

In [ ]:
dataset, info = tfds.load('imdb_reviews/subwords8k', with_info=True, as_supervised=True)

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Generating splits...:   0%|          | 0/3 [00:00<?, ? splits/s]

Generating train examples...:   0%|          | 0/25000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/imdb_reviews/subwords8k/1.0.0.incompleteYMSSH0/imdb_reviews-train.tfrecord…

Generating test examples...:   0%|          | 0/25000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/imdb_reviews/subwords8k/1.0.0.incompleteYMSSH0/imdb_reviews-test.tfrecord*…

Generating unsupervised examples...:   0%|          | 0/50000 [00:00<?, ? examples/s]

Shuffling /root/tensorflow_datasets/imdb_reviews/subwords8k/1.0.0.incompleteYMSSH0/imdb_reviews-unsupervised.t…

Dataset imdb_reviews downloaded and prepared to /root/tensorflow_datasets/imdb_reviews/subwords8k/1.0.0. Subsequent calls will reuse this data.


In [ ]:
train_dataset, test_dataset = dataset['train'], dataset['test']

In [ ]:
tokenizer = info.features['text'].encoder

In [ ]:
BUFFER_SIZE = 10000
BATCH_SIZE = 64

In [ ]:
train_dataset = train_dataset.shuffle(BUFFER_SIZE)

In [ ]:
len(train_dataset)

25000

In [ ]:
train_dataset = train_dataset.padded_batch(BATCH_SIZE)

In [ ]:
test_dataset = test_dataset.padded_batch(BATCH_SIZE)

In [ ]:
list(train_dataset)[0]

(<tf.Tensor: shape=(64, 1082), dtype=int64, numpy=
 array([[4555, 7961,  764, ...,    0,    0,    0],
        [7915, 7961,  279, ...,    0,    0,    0],
        [ 324,   12,   18, ...,    0,    0,    0],
        ...,
        [  12,  393,   14, ...,    0,    0,    0],
        [ 147,    4, 2621, ...,    0,    0,    0],
        [  62,   27,    9, ...,    0,    0,    0]])>,
 <tf.Tensor: shape=(64,), dtype=int64, numpy=
 array([1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
        0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
        0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1])>)

In [ ]:
list(train_dataset.take(1))

[(<tf.Tensor: shape=(64, 1368), dtype=int64, numpy=
  array([[  12,  207, 7968, ...,    0,    0,    0],
         [ 298,  662,    2, ...,    0,    0,    0],
         [ 133, 4583, 7961, ...,    0,    0,    0],
         ...,
         [5646,    2,    4, ...,    0,    0,    0],
         [ 133, 1392, 1394, ...,    0,    0,    0],
         [  12, 1012, 6765, ...,    0,    0,    0]])>,
  <tf.Tensor: shape=(64,), dtype=int64, numpy=
  array([1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
         0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
         0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1])>)]

# Simple RNN

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, RNN, Dense, LSTM, Bidirectional, SimpleRNN

In [ ]:
tokenizer.vocab_size

8185

In [ ]:
model1 = Sequential()
model1.add(Embedding(tokenizer.vocab_size, 64))
model1.add(SimpleRNN(32))


In [ ]:
8185 * 64

523840

In [ ]:
model1.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, None, 64)          523840    
                                                                 
 simple_rnn (SimpleRNN)      (None, 32)                3104      
                                                                 
Total params: 526944 (2.01 MB)
Trainable params: 526944 (2.01 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model1.add(Dense(16, activation='relu'))

In [ ]:
model1.add(Dense(1, activation='sigmoid'))

In [ ]:
model1.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])

In [ ]:
model1.fit(train_dataset, epochs=10, validation_data=test_dataset)

Epoch 1/10
391/391 [==============================] - 650s 2s/step - loss: 0.6938 - acc: 0.4996 - val_loss: 0.6932 - val_acc: 0.4998
Epoch 2/10
391/391 [==============================] - 622s 2s/step - loss: 0.6925 - acc: 0.5055 - val_loss: 0.6929 - val_acc: 0.5022
Epoch 3/10
391/391 [==============================] - 622s 2s/step - loss: 0.6917 - acc: 0.5002 - val_loss: 0.6929 - val_acc: 0.5024
Epoch 4/10
391/391 [==============================] - 600s 2s/step - loss: 0.6899 - acc: 0.4984 - val_loss: 0.6929 - val_acc: 0.5030
Epoch 5/10
391/391 [==============================] - 591s 2s/step - loss: 0.6879 - acc: 0.5048 - val_loss: 0.6931 - val_acc: 0.5025
Epoch 6/10
391/391 [==============================] - 588s 2s/step - loss: 0.6871 - acc: 0.5018 - val_loss: 0.6945 - val_acc: 0.4995
Epoch 7/10
391/391 [==============================] - 577s 1s/step - loss: 0.6917 - acc: 0.4996 - val_loss: 0.6931 - val_acc: 0.5030
Epoch 8/10
391/391 [==============================] - 604s 2s/step - 

# LSTM

In [ ]:
model2 = Sequential()
model2.add(Embedding(tokenizer.vocab_size, 64))
model2.add(LSTM(32))
model2.add(Dense(16, activation='relu'))
model2.add(Dense(1, activation='sigmoid'))

In [ ]:
model2.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, None, 64)          523840    
                                                                 
 lstm (LSTM)                 (None, 32)                12416     
                                                                 
 dense_2 (Dense)             (None, 16)                528       
                                                                 
 dense_3 (Dense)             (None, 1)                 17        
                                                                 
Total params: 536801 (2.05 MB)
Trainable params: 536801 (2.05 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model2.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])

In [ ]:
model2.fit(train_dataset, epochs=10, validation_data=test_dataset)

Epoch 1/10
391/391 [==============================] - 84s 205ms/step - loss: 0.6932 - acc: 0.5002 - val_loss: 0.6930 - val_acc: 0.5000
Epoch 2/10
391/391 [==============================] - 57s 146ms/step - loss: 0.6951 - acc: 0.5023 - val_loss: 0.6927 - val_acc: 0.5026
Epoch 3/10
391/391 [==============================] - 47s 120ms/step - loss: 0.6906 - acc: 0.5050 - val_loss: 0.6931 - val_acc: 0.5000
Epoch 4/10
391/391 [==============================] - 40s 102ms/step - loss: 0.6882 - acc: 0.5070 - val_loss: 0.6938 - val_acc: 0.5022
Epoch 5/10
391/391 [==============================] - 35s 89ms/step - loss: 0.6871 - acc: 0.5040 - val_loss: 0.6956 - val_acc: 0.5003
Epoch 6/10
391/391 [==============================] - 32s 81ms/step - loss: 0.6859 - acc: 0.5029 - val_loss: 0.6948 - val_acc: 0.5026
Epoch 7/10
391/391 [==============================] - 31s 80ms/step - loss: 0.6860 - acc: 0.5069 - val_loss: 0.6960 - val_acc: 0.5025
Epoch 8/10
391/391 [==============================] - 28s 

# Bidirectional

In [ ]:
model3 = Sequential()
model3.add(Embedding(tokenizer.vocab_size, 64))
model3.add(Bidirectional(LSTM(32)))
model3.add(Dense(32, activation='relu'))
model3.add(Dense(1, activation='sigmoid'))

In [ ]:
model3.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, None, 64)          523840    
                                                                 
 bidirectional (Bidirection  (None, 64)                24832     
 al)                                                             
                                                                 
 dense_4 (Dense)             (None, 32)                2080      
                                                                 
 dense_5 (Dense)             (None, 1)                 33        
                                                                 
Total params: 550785 (2.10 MB)
Trainable params: 550785 (2.10 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model3.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])

In [ ]:
model3.fit(train_dataset, epochs=10, validation_data=test_dataset)

Epoch 1/10
391/391 [==============================] - 101s 248ms/step - loss: 0.5229 - acc: 0.7298 - val_loss: 0.4295 - val_acc: 0.8131
Epoch 2/10
391/391 [==============================] - 75s 190ms/step - loss: 0.3225 - acc: 0.8752 - val_loss: 0.4073 - val_acc: 0.8287
Epoch 3/10
391/391 [==============================] - 62s 156ms/step - loss: 0.3324 - acc: 0.8698 - val_loss: 0.4380 - val_acc: 0.8308
Epoch 4/10
391/391 [==============================] - 57s 145ms/step - loss: 0.2382 - acc: 0.9136 - val_loss: 0.4154 - val_acc: 0.8293
Epoch 5/10
391/391 [==============================] - 53s 134ms/step - loss: 0.1827 - acc: 0.9379 - val_loss: 0.4475 - val_acc: 0.8398
Epoch 6/10
391/391 [==============================] - 51s 131ms/step - loss: 0.4658 - acc: 0.7739 - val_loss: 0.9032 - val_acc: 0.5588
Epoch 7/10
391/391 [==============================] - 49s 124ms/step - loss: 0.4691 - acc: 0.7746 - val_loss: 0.6110 - val_acc: 0.7128
Epoch 8/10
391/391 [==============================] - 

# Deep Bidirectional LSTM

In [ ]:
model4 = Sequential()
model4.add(Embedding(tokenizer.vocab_size, 64))
model4.add(Bidirectional(LSTM(64, return_sequences=True))) # (64 * 64 * 8 + 64 * 4) * 2
model4.add(Bidirectional(LSTM(32))) # (128 * 32 * 4 + 32 * 32 * 4 + 32 * 4) * 2
model4.add(Dense(32, activation='relu'))
model4.add(Dense(1, activation='sigmoid'))

In [ ]:
model4.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, None, 64)          523840    
                                                                 
 bidirectional_1 (Bidirecti  (None, None, 128)         66048     
 onal)                                                           
                                                                 
 bidirectional_2 (Bidirecti  (None, 64)                41216     
 onal)                                                           
                                                                 
 dense_6 (Dense)             (None, 32)                2080      
                                                                 
 dense_7 (Dense)             (None, 1)                 33        
                                                                 
Total params: 633217 (2.42 MB)
Trainable params: 63321

In [ ]:
model4.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])

In [ ]:
model4.fit(train_dataset, epochs=10, validation_data=test_dataset)

Epoch 1/10
391/391 [==============================] - 143s 346ms/step - loss: 0.5519 - acc: 0.7200 - val_loss: 0.5521 - val_acc: 0.7229
Epoch 2/10
391/391 [==============================] - 113s 290ms/step - loss: 0.3820 - acc: 0.8447 - val_loss: 0.4345 - val_acc: 0.8186
Epoch 3/10
391/391 [==============================] - 103s 263ms/step - loss: 0.3495 - acc: 0.8610 - val_loss: 0.5753 - val_acc: 0.6950
Epoch 4/10
391/391 [==============================] - 93s 238ms/step - loss: 0.3602 - acc: 0.8483 - val_loss: 0.5026 - val_acc: 0.7188
Epoch 5/10
391/391 [==============================] - 89s 227ms/step - loss: 0.3838 - acc: 0.8377 - val_loss: 0.5626 - val_acc: 0.7154
Epoch 6/10
391/391 [==============================] - 86s 220ms/step - loss: 0.4221 - acc: 0.8160 - val_loss: 0.4012 - val_acc: 0.8192
Epoch 7/10
391/391 [==============================] - 103s 264ms/step - loss: 0.2476 - acc: 0.9053 - val_loss: 0.3449 - val_acc: 0.8570
Epoch 8/10
391/391 [==============================]