In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [ ]:
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import precision_score, recall_score, f1_score #Classification Problem
from sklearn.metrics import plot_roc_curve

In [ ]:
dataset = pd.read_csv('/content/glass.csv', header=None)

In [ ]:
dataset.head()

0      1     2     3      4     5     6    7    8  9
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0  1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0  1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0  1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0  1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0  1

In [ ]:
for i in range(len(dataset.columns)):
    missing_data = dataset[dataset.columns[i]].isna().sum()
    perc = missing_data / len(dataset) * 100
    print('>%d,  missing entries: %d, percentage %.2f' % (i, missing_data, perc))

>0,  missing entries: 0, percentage 0.00
>1,  missing entries: 0, percentage 0.00
>2,  missing entries: 0, percentage 0.00
>3,  missing entries: 0, percentage 0.00
>4,  missing entries: 0, percentage 0.00
>5,  missing entries: 0, percentage 0.00
>6,  missing entries: 0, percentage 0.00
>7,  missing entries: 0, percentage 0.00
>8,  missing entries: 0, percentage 0.00
>9,  missing entries: 0, percentage 0.00


In [ ]:
X= dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)


In [ ]:
X

array([[ 0.87286765,  0.28495326,  1.25463857, ..., -0.14576634,
        -0.35287683, -0.5864509 ],
       [-0.24933347,  0.59181718,  0.63616803, ..., -0.79373376,
        -0.35287683, -0.5864509 ],
       [-0.72131806,  0.14993314,  0.60142249, ..., -0.82894938,
        -0.35287683, -0.5864509 ],
       ...,
       [ 0.75404635,  1.16872135, -1.86551055, ..., -0.36410319,
         2.95320036, -0.5864509 ],
       [-0.61239854,  1.19327046, -1.86551055, ..., -0.33593069,
         2.81208731, -0.5864509 ],
       [-0.41436305,  1.00915211, -1.86551055, ..., -0.23732695,
         3.01367739, -0.5864509 ]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.5, random_state = 1)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
logistic_clf = LogisticRegression()
logistic_clf.fit(X_train, y_train)

LogisticRegression()

In [ ]:
y_preds =logistic_clf.predict(X_test)

In [ ]:
# Display confusion matrix
print(confusion_matrix(y_test, y_preds))

[[25 11  0  0  0  0]
 [ 6 22  0  4  1  0]
 [ 3  7  0  0  0  0]
 [ 0  0  0  5  0  0]
 [ 0  1  0  0  3  0]
 [ 1  0  0  0  0 18]]


In [ ]:
print(classification_report(y_test, y_preds)) #Based on only 1 test set

              precision    recall  f1-score   support

           1       0.71      0.69      0.70        36
           2       0.54      0.67      0.59        33
           3       0.00      0.00      0.00        10
           5       0.56      1.00      0.71         5
           6       0.75      0.75      0.75         4
           7       1.00      0.95      0.97        19

    accuracy                           0.68       107
   macro avg       0.59      0.68      0.62       107
weighted avg       0.64      0.68      0.65       107



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
 from sklearn.svm import SVC
 from sklearn.tree import DecisionTreeClassifier
 from sklearn.ensemble import VotingClassifier

In [ ]:
estimator = []
estimator.append(('LR',
                  LogisticRegression(solver ='lbfgs',
                                     multi_class ='multinomial',
                                     max_iter = 20000)))
estimator.append(('SVC', SVC(gamma ='auto', probability = True)))
estimator.append(('DTC', DecisionTreeClassifier()))

# Voting Classifier with hard voting
vot_hard = VotingClassifier(estimators = estimator, voting ='hard')
vot_hard.fit(X_train, y_train)
y_pred_vote = vot_hard.predict(X_test)

In [ ]:
print(classification_report(y_test, y_pred_vote)) #Based on only 1 test set

              precision    recall  f1-score   support

           1       0.72      0.81      0.76        36
           2       0.64      0.76      0.69        33
           3       0.00      0.00      0.00        10
           5       0.71      1.00      0.83         5
           6       0.75      0.75      0.75         4
           7       1.00      0.89      0.94        19

    accuracy                           0.74       107
   macro avg       0.64      0.70      0.66       107
weighted avg       0.68      0.74      0.71       107



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
pd.DataFrame({'y': y_test,'y_preds':y_pred_vote})

y  y_preds
0    2        6
1    7        7
2    2        5
3    2        2
4    1        1
..  ..      ...
102  7        7
103  1        2
104  7        2
105  2        1
106  7        7

[107 rows x 2 columns]

In [ ]:
estimator = []
estimator.append(('LR',
                  LogisticRegression(solver ='lbfgs',
                                     multi_class ='multinomial',
                                     max_iter = 20000)))
estimator.append(('SVC', SVC(gamma ='auto', probability = True)))
estimator.append(('DTC', DecisionTreeClassifier()))

# Voting Classifier with hard voting
vot_hard = VotingClassifier(estimators = estimator, voting ='soft')
vot_hard.fit(X_train, y_train)
y_pred_vote1 = vot_hard.predict(X_test)

In [ ]:
print(classification_report(y_test, y_pred_vote1)) #Based on only 1 test set

              precision    recall  f1-score   support

           1       0.76      0.86      0.81        36
           2       0.68      0.70      0.69        33
           3       0.25      0.10      0.14        10
           5       0.71      1.00      0.83         5
           6       0.33      0.25      0.29         4
           7       0.89      0.84      0.86        19

    accuracy                           0.72       107
   macro avg       0.60      0.63      0.60       107
weighted avg       0.69      0.72      0.70       107

