In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data=pd.read_csv('/content/train.csv')

In [ ]:
data.head()

Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0   1          60       RL  ...        WD         Normal    208500
1   2          20       RL  ...        WD         Normal    181500
2   3          60       RL  ...        WD         Normal    223500
3   4          70       RL  ...        WD        Abnorml    140000
4   5          60       RL  ...        WD         Normal    250000

[5 rows x 81 columns]

In [ ]:
data=pd.read_csv('/content/train.csv',index_col="Id")

In [ ]:
data.head()

MSSubClass MSZoning  LotFrontage  ...  SaleType SaleCondition SalePrice
Id                                    ...                                  
1           60       RL         65.0  ...        WD        Normal    208500
2           20       RL         80.0  ...        WD        Normal    181500
3           60       RL         68.0  ...        WD        Normal    223500
4           70       RL         60.0  ...        WD       Abnorml    140000
5           60       RL         84.0  ...        WD        Normal    250000

[5 rows x 80 columns]

In [ ]:
data.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond',
       'PavedDrive', 'Wo

**2.Feature Selections**

In [ ]:
features = ["LotArea","YearBuilt","1stFlrSF","2ndFlrSF","FullBath","BedroomAbvGr","TotRmsAbvGrd"]


**3.Splitting dataset into X and y**

In [ ]:
X=data[features]
y=data["SalePrice"]

In [ ]:
X.head()

LotArea  YearBuilt  1stFlrSF  ...  FullBath  BedroomAbvGr  TotRmsAbvGrd
Id                                ...                                      
1      8450       2003       856  ...         2             3             8
2      9600       1976      1262  ...         2             3             6
3     11250       2001       920  ...         2             3             6
4      9550       1915       961  ...         1             3             7
5     14260       2000      1145  ...         2             4             9

[5 rows x 7 columns]

In [ ]:
y.head()

Id
1    208500
2    181500
3    223500
4    140000
5    250000
Name: SalePrice, dtype: int64

**X,y -> X_train,y_train,X_valid,y_valid**

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_valid,y_train,y_valid=train_test_split(X,y,train_size=0.8,test_size=0.2,random_state=0)

In [ ]:
X_train.shape

(1168, 7)

In [ ]:
X.shape

(1460, 7)

In [ ]:
data.shape

(1460, 80)

In [ ]:
X_valid.shape

(292, 7)

**4. Training Machine Learning Model**

In [ ]:
from sklearn.tree import  DecisionTreeRegressor
dt_model=DecisionTreeRegressor(random_state=1)

In [ ]:
dt_model.fit(X_train,y_train)

DecisionTreeRegressor(random_state=1)

In [ ]:
y_preds=dt_model.predict(X_valid.head())

In [ ]:
y_preds

array([335000., 140200., 119000., 207500., 112000.])

In [ ]:
pd.DataFrame({'y':y_valid.head(),'y_preds':y_preds})

y   y_preds
Id                   
530  200624  335000.0
492  133000  140200.0
460  110000  119000.0
280  192000  207500.0
656   88000  112000.0

In [ ]:
from sklearn.ensemble import RandomForestRegressor,GradientBoostingRegressor
rf_model=RandomForestRegressor(random_state=1)
rf_model.fit(X_train,y_train)

RandomForestRegressor(random_state=1)

In [ ]:
rf_val_preds=rf_model.predict(X_valid)

In [ ]:
rf_val_preds[:5]

array([271690., 155039., 122024., 188915.,  91147.])

**Predict with a new input**

In [ ]:
rf_model.predict([[6969,2021,1000,800,4,5,8]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  "X does not have valid feature names, but"


array([206158.4])