In [ ]:
import sys
import numpy as np

# Basic Numpy Arrays

In [ ]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [ ]:

a = np.array([1, 2, 3, 4])

In [ ]:
b = np.array([0, .5, 1, 1.5, 2])

In [ ]:

a[0], a[1]

(1, 2)

In [ ]:
a[0:]

array([1, 2, 3, 4])

In [ ]:

a[1:3]

array([2, 3])

In [ ]:
a[1:-1]

array([2, 3])

In [ ]:
a[::2]

array([1, 3])

In [ ]:

b

array([0. , 0.5, 1. , 1.5, 2. ])

In [ ]:

# Multi-index
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [ ]:
b[[0, 2, -1]]

array([0., 1., 2.])

# Array Types

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [ ]:
b.dtype

dtype('float64')

In [ ]:
np.array([1, 2, 3, 4], dtype=np.float)

array([1., 2., 3., 4.])

In [ ]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [ ]:
c = np.array(['a', 'b', 'c'])

In [ ]:
c.dtype

dtype('<U1')

In [ ]:
d = np.array([{'a': 1}, sys])

In [ ]:
d.dtype

dtype('O')

# Dimensions and shapes

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [ ]:
A.shape

(2, 3)

In [ ]:
A.ndim

2

In [ ]:
A.size

6

In [ ]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [ ]:

B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [ ]:
B.shape

(2, 2, 3)

In [ ]:
B.ndim


3

In [ ]:
B.size

12

# Nếu hình dạng không nhất quán, nó sẽ chỉ trở lại các đối tượng Python thông thường

In [ ]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  import sys


In [ ]:
C.dtype

dtype('O')

In [ ]:
C.shape

(2,)

In [ ]:
C.size

2

In [ ]:

type(C[0])

list

# Indexing and Slicing of Matrices

In [ ]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [ ]:
A[1]

array([4, 5, 6])

In [ ]:
A[1][0]

4

In [ ]:
A[1, 0]

4

In [ ]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [ ]:
A[:2, 2:]

array([[3],
       [6]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
A[1] = np.array([10, 10, 10])

In [ ]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [ ]:
A[2] = 99

In [ ]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

# Summary statistics

In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
a.sum()

10

In [ ]:
a.mean()

2.5

In [ ]:
a.std()

1.118033988749895

In [ ]:
a.var()

1.25

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:

A.sum()

45

In [ ]:

A.mean()

5.0

In [ ]:
A.std()

2.581988897471611

In [ ]:
A.sum(axis=0)

array([12, 15, 18])

In [ ]:
A.sum(axis=1)

array([ 6, 15, 24])

In [ ]:
A.mean(axis=0)

array([4., 5., 6.])

In [ ]:
A.mean(axis=1)

array([2., 5., 8.])

In [ ]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [ ]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

# Các hoạt động truyền phát và Vectorized

In [ ]:
a = np.arange(4)

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
a + 10

array([10, 11, 12, 13])

In [ ]:
a * 10

array([ 0, 10, 20, 30])

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
a += 100

In [ ]:
a

In [ ]:
l = [0, 1, 2, 3]

In [ ]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [ ]:
a = np.arange(4)

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
b = np.array([10, 10, 10, 10])

In [ ]:
b

array([10, 10, 10, 10])

In [ ]:
a + b

array([10, 11, 12, 13])

In [ ]:
a * b

array([ 0, 10, 20, 30])

# Boolean arrays

In [ ]:
a = np.arange(4)

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
a[0], a[-1]

(0, 3)

In [ ]:
a[[0, -1]]

array([0, 3])

In [ ]:
a[[True, False, False, True]]

array([0, 3])

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
a >= 2

array([False, False,  True,  True])

In [ ]:
a[a >= 2]

array([2, 3])

In [ ]:
a.mean()

1.5

In [ ]:
a[a > a.mean()]

array([2, 3])

In [ ]:
a[~(a > a.mean())]

array([0, 1])

In [ ]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [ ]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [ ]:
A = np.random.randint(100, size=(3, 3))

In [ ]:
A

array([[94, 77,  9],
       [25,  3, 89],
       [97, 40, 36]])

In [ ]:

A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([94,  9,  3, 97, 36])

In [ ]:
A > 30

array([[ True,  True, False],
       [False, False,  True],
       [ True,  True,  True]])

In [ ]:

A[A > 30]

array([94, 77, 89, 97, 40, 36])

**Đại số tuyến tính**

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [ ]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

# **Size of objects in Memory**
# Int, floats

In [ ]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [ ]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [ ]:
# Numpy size is much smaller
np.dtype(int).itemsize

8

In [ ]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [ ]:
np.dtype(float).itemsize

8

### **Lists are even larger**

In [ ]:
# A one-element list
sys.getsizeof([1])

80

In [ ]:
# An array of one element in numpy
np.array([1]).nbytes

8

 And performance is also **important**

In [ ]:
l = list(range(100000))

In [ ]:
a = np.arange(100000)

In [ ]:
%time np.sum(a ** 2)

CPU times: user 2.26 ms, sys: 0 ns, total: 2.26 ms
Wall time: 2.36 ms


333328333350000

In [ ]:
%time sum([x ** 2 for x in l])

CPU times: user 33.3 ms, sys: 5.89 ms, total: 39.2 ms
Wall time: 47.1 ms


333328333350000

# Useful Numpy functions
**random**

In [ ]:
np.random.random(size=2)

array([0.10449179, 0.21704661])

In [ ]:
np.random.normal(size=2)

array([-0.09231277, -1.12283721])

In [ ]:
np.random.rand(2, 4)

array([[0.99191945, 0.94506889, 0.81081873, 0.55269383],
       [0.42051757, 0.07630946, 0.08498222, 0.50549742]])

# **arange**

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

# **reshape**

In [ ]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

# **linspace**

In [ ]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:

np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

# ***zeros, ones, empty***

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:

np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((3, 3), dtype=np.int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [ ]:

np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

# **identity and eye**

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [ ]:
"Hello World"[6]

'W'